#!/usr/bin/env node
// Inline the shared MusicBrainz request gate (dev/net/mb-gate.mjs) into every script
// that opts in with a marker block. #633
//
//   // <ST-NET> …generated, do not edit… // </ST-NET>
//
// The same mechanism as the shared matching (dev/match/sync-match.mjs): the source is a
// real ES module, which Credit Hoarder's esbuild imports directly, so the block is
// generated from each function's own source text.
//
// Run:  node dev/net/sync-gate.mjs      (the pre-commit hook runs it automatically)
// Edit dev/net/mb-gate.mjs, NEVER the generated blocks.

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, join } from 'node:path';
import { MBN_INLINE } from './mb-gate.mjs';

// Write the file in its own line endings. The generated block comes from a source file
// that may be CRLF on a Windows checkout while the target is LF (or the other way round);
// a mixed file is stored by Git with its carriage returns, and every line of it shows as
// changed (#623).
function sameEol(next, src) {
    const crlf = (src.match(/\r\n/g) || []).length, lf = (src.match(/\n/g) || []).length;
    const flat = next.replace(/\r*\n/g, '\n');   // \r*: a CRLF source's lines can arrive as \r\r\n
    return crlf * 2 > lf ? flat.replace(/\n/g, '\r\n') : flat;
}

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..', '..');
const START = '// <ST-NET>';
const END = '// </ST-NET>';

const lines = [`${START} — generated by dev/net/sync-gate.mjs from dev/net/mb-gate.mjs — DO NOT EDIT`];
for (const [k, v] of Object.entries(MBN_INLINE.consts)) {
    lines.push(`const ${k} = ${typeof v === 'number' ? v : Array.isArray(v) ? 'new Set(' + JSON.stringify(v) + ')' : JSON.stringify(v)};`);
}
for (const fn of MBN_INLINE.fns) {
    const src = fn.toString();
    if (!/^(async )?function mbn\w+\(/.test(src)) { console.error('✗ ' + fn.name + ' must be a plain `function mbn…()` declaration'); process.exit(1); }
    lines.push(...src.split('\n'));
}
lines.push(END);

const esc = s => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const BLOCK_RE = new RegExp(`([ \\t]*)${esc(START)}[^\\n]*\\n[\\s\\S]*?${esc(END)}[^\\n]*`);

function walk(dir, out = []) {
    for (const name of readdirSync(dir)) {
        if (name === 'node_modules' || name === '.git' || name === 'dist' || name === 'string_theory.user.js' || name.endsWith('.pw-profile')) continue;
        const p = join(dir, name);
        if (statSync(p).isDirectory()) walk(p, out);
        else if (/\.js$/.test(name)) out.push(p);
    }
    return out;
}

const updated = [];
let carriers = 0;
for (const file of walk(resolve(ROOT, 'userscripts'))) {
    let src;
    try { src = readFileSync(file, 'utf8'); } catch (e) { continue; }
    if (!src.includes(START)) continue;
    carriers++;
    const indent = (src.match(BLOCK_RE) || [])[1] || '';
    const crlf = src.includes('\r\n');
    const block = lines.map(l => l ? indent + l : l).join(crlf ? '\r\n' : '\n');
    const next = src.replace(BLOCK_RE, () => block);
    const out = sameEol(next, src);
    if (out !== src) { writeFileSync(file, out); updated.push(file.replace(ROOT, '').replace(/\\/g, '/')); }
}
console.log(`✓ request gate synced — ${carriers} file(s) carry the marker, ${updated.length} rewritten:`);
for (const f of updated) console.log('  · ' + f);
if (!carriers) console.log('  (no files carry a // <ST-NET> marker yet)');
