#!/usr/bin/env node
// Inline the shared UI components (dev/ui-components.mjs) into every script
// that opts in with a marker block. #563
//
//   // <ST-UI> …generated, do not edit… // </ST-UI>
//
// Same mechanism as the shared platform icons (#404) and design tokens (#562):
// a script adds the two marker lines once, this codegen fills everything between
// with `const MBU_UI_CSS = '…'` plus the component helpers. No runtime
// dependency, no build step for the consumer.
//
// Run:  node dev/sync-ui.mjs         (the pre-commit hook runs it automatically)
// Edit components in dev/ui-components.mjs, NEVER the generated blocks.

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, join } from 'node:path';
import { UI_CSS, UI_JS } from './ui-components.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const START = '// <ST-UI>';
const END = '// </ST-UI>';

if (/['\\\n]/.test(UI_CSS)) {
    console.error('✗ UI_CSS contains a quote, backslash or newline — it is emitted as a single-quoted string. Fix dev/ui-components.mjs');
    process.exit(1);
}

const body = [
    `${START} — generated by dev/sync-ui.mjs from dev/ui-components.mjs — DO NOT EDIT`,
    `const MBU_UI_CSS = '${UI_CSS}';`,
    ...UI_JS.split('\n'),
    END,
];

const esc = s => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const BLOCK_RE = new RegExp(`([ \\t]*)${esc(START)}[^\\n]*\\n[\\s\\S]*?${esc(END)}[^\\n]*`);

function walk(dir, out = []) {
    for (const name of readdirSync(dir)) {
        if (name === 'node_modules' || name === '.git' || name === 'dist' || name === 'string_theory.user.js' || name.endsWith('.pw-profile')) continue;
        const p = join(dir, name);
        if (statSync(p).isDirectory()) walk(p, out);
        else if (/\.js$/.test(name)) out.push(p);
    }
    return out;
}

const updated = [];
let carriers = 0;
for (const file of walk(resolve(ROOT, 'userscripts'))) {
    let src;
    try { src = readFileSync(file, 'utf8'); } catch (e) { continue; }
    if (!src.includes(START)) continue;
    carriers++;
    const indent = (src.match(BLOCK_RE) || [])[1] || '';
    // Blank lines stay blank — indenting them just adds trailing whitespace.
    const block = body.map(l => (l === '' ? '' : indent + l)).join('\n');
    const next = src.replace(BLOCK_RE, block);
    if (next !== src) { writeFileSync(file, next); updated.push(file.replace(ROOT + '\\', '').replace(ROOT + '/', '')); }
}

console.log(`✓ UI components synced — ${carriers} file(s) carry the marker, ${updated.length} rewritten:`);
for (const f of updated) console.log('  · ' + f.replace(/\\/g, '/'));
if (!carriers) console.log('  (no files carry a // <ST-UI> marker yet)');
