#!/usr/bin/env node
// Inline the shared design tokens (dev/tokens/design-tokens.mjs) into every script
// that opts in with a marker block. #562
//
//   // <ST-TOKENS> …generated, do not edit… // </ST-TOKENS>
//
// A script adds those two marker lines once; this codegen fills everything
// between with `const MBU_TOKENS = ':root{--mbu-…}'`, which the script
// prepends to its own stylesheet. No runtime dependency, no build step for
// the consumer — the same shape as dev/ui/sync-icons.mjs (#404).
//
// Run:  node dev/tokens/sync-tokens.mjs      (the pre-commit hook runs it automatically)
// Edit values in dev/tokens/design-tokens.mjs, NEVER the generated blocks.

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, join } from 'node:path';
import { tokensCss } from './design-tokens.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..', '..');   // dev/<subsystem>/ -> repo root
const START = '// <ST-TOKENS>';
const END = '// </ST-TOKENS>';

// Single-quoted string literal; the token values contain no quotes or backslashes
// (asserted below) so the block stays trivially portable into any script.
const css = tokensCss();
if (/['\\\n]/.test(css)) {
    console.error('✗ a token value contains a quote, backslash or newline — fix dev/tokens/design-tokens.mjs');
    process.exit(1);
}
const body = [
    `// <ST-TOKENS> — generated by dev/tokens/sync-tokens.mjs from dev/tokens/design-tokens.mjs — DO NOT EDIT`,
    `const MBU_TOKENS = '${css}';`,
    `// </ST-TOKENS>`,
];

const esc = s => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const BLOCK_RE = new RegExp(`([ \\t]*)${esc(START)}[^\\n]*\\n[\\s\\S]*?${esc(END)}[^\\n]*`);

function walk(dir, out = []) {
    for (const name of readdirSync(dir)) {
        // skip deps, VCS, generated dist/, and the generated String Theory bundle
        // (build.mjs regenerates it from members — syncing it here would only patch
        // its first inlined block and fight the rebuild).
        if (name === 'node_modules' || name === '.git' || name === 'dist' || name === 'string_theory.user.js' || name.endsWith('.pw-profile')) continue;
        const p = join(dir, name);
        if (statSync(p).isDirectory()) walk(p, out);
        else if (/\.js$/.test(name)) out.push(p);
    }
    return out;
}

const updated = [];
let carriers = 0;
for (const file of walk(resolve(ROOT, 'userscripts'))) {
    let src;
    try { src = readFileSync(file, 'utf8'); } catch (e) { continue; }
    if (!src.includes(START)) continue;
    carriers++;
    const indent = (src.match(BLOCK_RE) || [])[1] || '';
    const next = src.replace(BLOCK_RE, body.map(l => indent + l).join('\n'));
    if (next !== src) { writeFileSync(file, next); updated.push(file.replace(ROOT + '\\', '').replace(ROOT + '/', '')); }
}

console.log(`✓ design tokens synced — ${carriers} file(s) carry the marker, ${updated.length} rewritten:`);
for (const f of updated) console.log('  · ' + f.replace(/\\/g, '/'));
if (!carriers) console.log('  (no files carry a // <ST-TOKENS> marker yet)');
