#!/usr/bin/env node
// Inline the shared matching functions (dev/match/artist-match.mjs) into every script
// that opts in with a marker block. #613
//
//   // <ST-MATCH> …generated, do not edit… // </ST-MATCH>
//
// Same mechanism as the shared icons (#404), tokens (#562) and UI (#563): a script adds
// the two marker lines once and this codegen fills them. Unlike those, the source here
// is a real ES module — node tests and Credit Hoarder's esbuild import it directly —
// so the block is generated from each function's own source text.
//
// Run:  node dev/match/sync-match.mjs      (the pre-commit hook runs it automatically)
// Edit dev/match/artist-match.mjs, NEVER the generated blocks.

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, join } from 'node:path';
import { MBM_INLINE } from './artist-match.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..', '..');
const START = '// <ST-MATCH>';
const END = '// </ST-MATCH>';

const lines = [`${START} — generated by dev/match/sync-match.mjs from dev/match/artist-match.mjs — DO NOT EDIT`];
for (const [k, v] of Object.entries(MBM_INLINE.consts)) {
    lines.push(`const ${k} = ${typeof v === 'number' ? v : Array.isArray(v) ? 'new Set(' + JSON.stringify(v) + ')' : JSON.stringify(v)};`);
}
for (const fn of MBM_INLINE.fns) {
    const src = fn.toString();
    if (!/^function mbm\w+\(/.test(src)) { console.error('✗ ' + fn.name + ' must be a plain `function mbm…()` declaration'); process.exit(1); }
    lines.push(...src.split('\n'));
}
lines.push(END);

// NB MBM_SPECIAL_PURPOSE is an array in the module (importable, JSON-able) and a Set in
// the generated block — the scripts test membership with .has().
const esc = s => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const BLOCK_RE = new RegExp(`([ \\t]*)${esc(START)}[^\\n]*\\n[\\s\\S]*?${esc(END)}[^\\n]*`);

function walk(dir, out = []) {
    for (const name of readdirSync(dir)) {
        if (name === 'node_modules' || name === '.git' || name === 'dist' || name === 'string_theory.user.js' || name.endsWith('.pw-profile')) continue;
        const p = join(dir, name);
        if (statSync(p).isDirectory()) walk(p, out);
        else if (/\.js$/.test(name)) out.push(p);
    }
    return out;
}

const updated = [];
let carriers = 0;
for (const file of walk(resolve(ROOT, 'userscripts'))) {
    let src;
    try { src = readFileSync(file, 'utf8'); } catch (e) { continue; }
    if (!src.includes(START)) continue;
    carriers++;
    const indent = (src.match(BLOCK_RE) || [])[1] || '';
    const crlf = src.includes('\r\n');
    const block = lines.map(l => l ? indent + l : l).join(crlf ? '\r\n' : '\n');
    const next = src.replace(BLOCK_RE, () => block);
    if (next !== src) { writeFileSync(file, next); updated.push(file.replace(ROOT, '').replace(/\\/g, '/')); }
}
console.log(`✓ matching synced — ${carriers} file(s) carry the marker, ${updated.length} rewritten:`);
for (const f of updated) console.log('  · ' + f);
if (!carriers) console.log('  (no files carry a // <ST-MATCH> marker yet)');
