#!/usr/bin/env node
// Inline the shared platform-icon set (dev/ui/platform-icons.mjs) into every script
// that opts in with a marker block. #404
//
//   // <ST-ICONS> …generated, do not edit… // </ST-ICONS>
//
// A script adds those two marker lines once; this codegen fills everything between
// with `const ST_ICONS = {…}` + `stIcon()`/`stColor()` helpers, so every script
// draws the same brand icon at the same size with no runtime dependency.
//
// Run:  node dev/ui/sync-icons.mjs        (the pre-commit hook runs it automatically)
// Edit icons in dev/ui/platform-icons.mjs, NEVER the generated blocks.

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, join } from 'node:path';
import { PLATFORM_ICONS } from './platform-icons.mjs';

// Write the file in its own line endings. The generated block comes from a source file
// that may be CRLF on a Windows checkout while the target is LF (or the other way round);
// a mixed file is stored by Git with its carriage returns, and every line of it shows as
// changed (#623).
function sameEol(next, src) {
    const crlf = (src.match(/\r\n/g) || []).length, lf = (src.match(/\n/g) || []).length;
    const flat = next.replace(/\r*\n/g, '\n');   // \r*: a CRLF source's lines can arrive as \r\r\n
    return crlf * 2 > lf ? flat.replace(/\n/g, '\r\n') : flat;
}

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..', '..');   // dev/<subsystem>/ -> repo root
const START = '// <ST-ICONS>';
const END = '// </ST-ICONS>';

// The generated body (marker-free). ST_ICONS is compact JSON; the helpers use
// string concat (no template literals) so the block is trivially portable.
const body = [
    `// <ST-ICONS> — generated by dev/ui/sync-icons.mjs from dev/ui/platform-icons.mjs — DO NOT EDIT`,
    `const ST_ICONS = ${JSON.stringify(PLATFORM_ICONS)};`,
    `function stIcon(name, size) { var i = ST_ICONS[name]; if (!i) return ''; size = size || 16; return i.svg.replace(/<svg\\b([^>]*)>/, function (m, a) { a = a.replace(/\\s(?:width|height)="[^"]*"/g, ''); var ns = /\\bxmlns=/.test(a) ? '' : ' xmlns="http://www.w3.org/2000/svg"'; return '<svg' + a + ns + ' width="' + size + '" height="' + size + '">'; }); }`,
    `function stColor(name) { return (ST_ICONS[name] && ST_ICONS[name].color) || ''; }`,
    `// </ST-ICONS>`,
];

// Replace a marker block, re-indented to the START marker's own indentation.
const BLOCK_RE = new RegExp(`([ \\t]*)${START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[^\\n]*\\n[\\s\\S]*?${END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[^\\n]*`);

function walk(dir, out = []) {
    for (const name of readdirSync(dir)) {
        // skip deps, VCS, generated dist/, and the generated String Theory bundle
        // (build.mjs regenerates it from members — syncing it here would only patch
        // its first inlined block and fight the rebuild).
        if (name === 'node_modules' || name === '.git' || name === 'dist' || name === 'string_theory.user.js' || name.endsWith('.pw-profile')) continue;
        const p = join(dir, name);
        const st = statSync(p);
        if (st.isDirectory()) walk(p, out);
        else if (/\.(user\.)?js$/.test(name) || name.endsWith('.js')) out.push(p);
    }
    return out;
}

const updated = [];
for (const file of walk(resolve(ROOT, 'userscripts'))) {
    let src;
    try { src = readFileSync(file, 'utf8'); } catch (e) { continue; }
    if (!src.includes(START)) continue;
    const indent = (src.match(BLOCK_RE) || [])[1] || '';
    const block = body.map((l, i) => (i === 0 || l === '' ? indent + l : indent + l)).join('\n');
    const next = src.replace(BLOCK_RE, block);
    const out = sameEol(next, src);
    if (out !== src) { writeFileSync(file, out); updated.push(file.replace(ROOT + '\\', '').replace(ROOT + '/', '')); }
}

console.log(`✓ platform icons synced into ${updated.length} file(s):`);
for (const f of updated) console.log('  · ' + f.replace(/\\/g, '/'));
if (!updated.length) console.log('  (no files carry a // <ST-ICONS> marker yet)');
