// Builds the consolidation mockups (#702): writes icons.js from the shared platform
// icons, then a PNG of every *.html here. Run: node dev/mockups/mission_control/consolidate/build.mjs
import fs from 'fs';
import path from 'path';
import { fileURLToPath, pathToFileURL } from 'url';
import { chromium } from '@playwright/test';
import { PLATFORM_ICONS } from '../../../ui/platform-icons.mjs';

const dir = path.dirname(fileURLToPath(import.meta.url));
const icons = Object.fromEntries(Object.entries(PLATFORM_ICONS).map(([k, v]) => [k, v.svg]));
fs.writeFileSync(path.join(dir, 'icons.js'), '// generated by build.mjs from dev/ui/platform-icons.mjs\nwindow.ST_ICONS = ' + JSON.stringify(icons) + ';\n');

const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1600, height: 500 }, deviceScaleFactor: 1 });
for (const f of fs.readdirSync(dir).filter(f => f.endsWith('.html') && (!process.argv[2] || f.startsWith(process.argv[2])))) {
  await page.goto(pathToFileURL(path.join(dir, f)).href);
  await page.screenshot({ path: path.join(dir, f.replace(/\.html$/, '.png')), fullPage: true });
  console.log('shot', f);
}
await browser.close();
