#!/usr/bin/env node
// Inline lande, the language detector Harmony uses, into Apollo (#703):
//
//   // <LANDE> …generated, do not edit… // </LANDE>
//
// lande is pinned in package.json; rerun only to change its version.
// Run:  pnpm vendor:lande   (in userscripts/apollo_editor)

import { build } from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const TARGET = resolve(HERE, '..', 'apollo_editor.user.js');
const version = JSON.parse(readFileSync(resolve(HERE, '..', 'node_modules', 'lande', 'package.json'), 'utf8')).version;

const out = await build({
  stdin: { contents: "import lande from 'lande'; export default lande;", resolveDir: HERE, loader: 'js' },
  bundle: true, minify: true, format: 'iife', globalName: '__lande', target: 'es2019', write: false, legalComments: 'none',
});
const code = out.outputFiles[0].text.trim();

const src = readFileSync(TARGET, 'utf8');
const eol = (src.match(/\r\n/g) || []).length * 2 > (src.match(/\n/g) || []).length ? '\r\n' : '\n';
const re = /([ \t]*)\/\/ <LANDE>[^\n]*\n[\s\S]*?\/\/ <\/LANDE>/;
const m = src.match(re); if (!m) { console.error('no // <LANDE> block in', TARGET); process.exit(1); }
const ind = m[1];
// built on first use: the model's weights are parsed only when a language is wanted
const block = [
  `${ind}// <LANDE> — lande ${version} (MIT, github.com/fabiospampinato/lande), generated by dev/build-lande.mjs — DO NOT EDIT`,
  `${ind}// eslint-disable-next-line`,
  `${ind}const landeLoad = () => { ${code} return __lande.default; };`,
  `${ind}// </LANDE>`,
].join(eol);
writeFileSync(TARGET, src.replace(re, () => block));
console.log(`lande ${version}: ${Math.round(code.length / 1024)} KB inlined into`, TARGET);
